### ISSUE TITLE
[DETECTION]  in relation with requests : POST no longer detects the correct charset ( data with é )

### ISSUE THREAD

**Issue by el-dge** [Ousret/charset_normalizer#290]
With new version, the header _Content-Type_ is not set good (not set at all).
I have an **é** in the data post.

## Expected Result
In the headers :
`'Content-Type': 'text/plain; charset=UTF-8'`

## Actual Result
Header _Content-Type_ is not set, Requests not recognize **é** in data and don't add  `'Content-Type': 'text/plain; charset=UTF-8'`

## Reproduction Steps

```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ").text
```
bad response: `'[2,"\\u00C3\\u00A9"]'`
[Here for explication of the response](https://www.warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/09_Analysing_data#encoding)

I must specify header (not need before, one week ago):
```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ", headers={'Content-Type': 'text/plain; charset=UTF-8'}).text
```
good response : `'[1,"\\u00E9"]'`
## System Information

    $ python -m requests.help

```json
/usr/lib64/python3.9/site-packages/requests/help.py:24: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in urllib3 v2.1.0. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib import pyopenssl
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": "40.0.2"
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.9.16"
  },
  "platform": {
    "release": "5.15.94",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "30100000",
    "version": "23.1.1"
  },
  "requests": {
    "version": "2.30.0"
  },
  "system_ssl": {
    "version": "1010114f"
  },
  "urllib3": {
    "version": "2.0.2"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": true
}

```

Server attempt a header charset of utf-8 if  my data's request has non ASCII character, thing that _charset-normalizer_ no longer does)
```python
>>> requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ", headers={'Content-Type': 'text/plain; charset=UTF-8'}).json()
[1, 'é']
>>> requests.post('https://warp.senx.io/api/v0/exec', data="'é' DUP SIZE ").json()
[2, 'Ã©']
```

An another bypass solution is:
```python
import requests

requests.post('https://warp.senx.io/api/v0/exec', data="'%C3%A9' DUP SIZE ").text
```
good response : `'[1,"\\u00E9"]'`
Thx in advance.

**Comment by el-dge** [comment]
I have add comments in the request if _charset_normalizer_ lacks some contexts but same result (I make the data best):
```python
data=bytes("\n//éàùè^&∅··\n// ùùù₂\n'é' DUP SIZE", 'utf-8')
>>> requests.post('https://warp.senx.io/api/v0/exec', data=data).json()
[2, 'Ã©']
>>> requests.post('https://warp.senx.io/api/v0/exec', data=data, headers={'content-type':'text/plain; charset=UTF-8'}).json()
[1, 'é']
```
Last response is the good

**Comment by Ousret** [comment]
Hello,

I understand you came/redirected from https://github.com/psf/requests/issues/6447
The initial investigation was incomplete, this case is interesting. I'll try to understand this better.

### POST request to server.xyz

You have to know that you are sending a payload with an unknown encoding, the server has to wild guess it or assume everything is charset _X_. Neither requests nor charset-normalizer can do it for you.

When you add `headers={'content-type':'text/plain; charset=UTF-8'}`, you simply tell the server what encoding your payload is. And the server assumes that you want a response based on that encoding.

### Decoding the API response (JSON)

#### No content-type prior to

Now, IF we don't specify the input charset, it seems to assume ASCII to transfer the response.
Look carefully,

```python
data=bytes("\n//éàùè^&∅··\n// ùùù₂\n'é' DUP SIZE", 'utf-8')
requests.post('https://warp.senx.io/api/v0/exec', data=data).content
```

content output `b'[2,"\\u00C3\\u00A9"]'` which is valid JSON. I suspect that the '2' is the length of the second value.
 
calling .headers shows

```python
{'Connection': 'close', 'Date': 'Sun, 07 May 2023 04:38:25 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'X-Warp10-Elapsed,X-Warp10-Ops,X-Warp10-Fetched', 'X-Warp10-Elapsed': '56635', 'X-Warp10-Ops': '4', 'X-Warp10-Fetched': '0', 'Vary': 'Accept-Encoding, User-Agent', 'Content-Encoding': 'gzip'}
```

There is no Content-Type!

requests do not guess the encoding when you call the method `.json()` as far as I know.

#### Content-type prior to

```python
resp = requests.post('https://warp.senx.io/api/v0/exec', data=data, headers={'content-type':'text/plain; charset=UTF-8'})
resp.content
b'[1,"\\u00E9"]'
```

Here the `\\u00E9` is a valid utf-8 codepoint and its len is indeed 1 printable character. Before it took your payload as ASCII and 'é' is indeed two bytes.

```python
'é'.encode('utf-8')
b'\xc3\xa9'
```

now the `b'[2,"\\u00C3\\u00A9"]'` makes sense.

...headers

```
{'Connection': 'close', 'Date': 'Sun, 07 May 2023 04:41:29 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'X-Warp10-Elapsed,X-Warp10-Ops,X-Warp10-Fetched', 'X-Warp10-Elapsed': '52865', 'X-Warp10-Ops': '4', 'X-Warp10-Fetched': '0', 'Vary': 'Accept-Encoding, User-Agent', 'Content-Encoding': 'gzip'}
```

Still no content type. The server needs to set it! It serves JSON without explicit encoding.

### What about charset-normalizer?

In the original issue, I saw that your environment had `chardet` installed then here, not anymore. I suspect that you removed it since.

- according to `requests` code `json()` method call function `guess_json_utf(data)` if there is no encoding predefined which does not rely on us.
- if we feed manually `b'[2,"\\u00C3\\u00A9"]'` to charset-normalizer is says **ASCII** and it is correct.
- if we feed manually `b'[1,"\\u00E9"]'` to charset-normalizer is says **UTF-8** and it is correct.
- guess JSON encoding is pretty much borderline and must be used as a last resort.


Hope this elude your situation.
Regards,

**Comment by el-dge** [comment]
Merci bien pour la réponse, je vais essayer de trouver un autre serveur, là la réponse ajoute de la confusion sur ce qui est réellement envoyé par requests.
Et en effet, j'ai désinstallé chardet entre temps.

**Comment by el-dge** [comment]
I have resumed my problem :
```python
import requests
requests.post('https://httpbin.org/post', data=bytes('ééééàààà', 'utf-8')).json()
{'args': {}, 'data': 'ééééàààà', 'files': {}, 'form': {}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '16', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.30.0', 'X-Amzn-Trace-Id': 'Root=1-64593102-0fd37eb93505b2696532fcae'}, 'json': None, 'origin': '45.13.y.x', 'url': 'https://httpbin.org/post'}
```
Why _requests_ don't add `Content-Type': 'text/plain; charset=UTF-8`  , whereas _charset_normalizer_ detects `ééééàààà` as utf-8 ? ( Or fallback `application/octet-stream` if none detect )
Maybe I make a mistake on the internal functioning of  _requests_. Maybe we must specify the correct headers content-type (with charset) and requests don't realize auto-detection of POST's data with _charset_normalizer_.

**Comment by Ousret** [comment]
At the very moment you specified `data=...` you are on your own.
requests cannot magically infer what you want or mean. 

it adds `Content-Type` when the intention is supervised by RFCs. Like when you use `json={...}`.

Hope that clarify,
If you need further inquiry for requests, please, use specialized websites for it.

regards,

**Comment by el-dge** [comment]
Without bytes (and charset),  : 
```python
requests.post('https://httpbin.org/post', data='ééééààààùùùù').json()
{'args': {}, 'data': 'ééééàà', 'files': {}, 'form': {}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '12', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.30.0', 'X-Amzn-Trace-Id': 'Root=1-6459f1ae-68860dce4043745d60173eef'}, 'json': None, 'origin': '45.13.x.y', 'url': 'https://httpbin.org/post'}
```
(data is truncate)

Something has changed 10 days ago (before my script was ok), I don't know if it's the server or requests or ...
But ok, I 'll add now manually _content-type_ for this type of POST's data.

Thank a lot, for your responses and patience. It's nice.

Cordialement.
