### ISSUE TITLE
Receive userWarning: Charset-Normalizer require 'C:\Users\juergens\AppData\Local\Temp\_MEI143042\charset_normalizer\assets/frequencies.json'

### ISSUE THREAD

**Issue by hjs-develop** [Ousret/charset_normalizer#86]
**Describe the bug**
A package has dependency to charset-normalizer 2.0.4
We use Pyinstaller to package our application into an EXEcutable.

Executing the EXE brings this waring:
_charset_normalizer\assets\__init__.py:17: UserWarning: Charset-Normalizer require 'C:\Users\juergens\AppData\Local\Temp\_MEI143042\charset_normalizer\assets/frequencies.json' to be existent for language/coherence detection. Detection WILL be weaker._ 

**Expected behavior**
No warning.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 2.9.1
 - Package version 2.0.4

**Additional context**
The requested JSON frequencies.json is not found in the Conda package of v2.0.4, nor found in teg Github repo of charset-normalizer.
The folder charset_normalizer\assets only includes the \__init\__.py file.

The folder Temp\_MEI143042 is created by PYinstaller to unpack the EXE into a temp folder before execution.

**Comment by Ousret** [comment]
Hi,

This should not happen. The package is no longer dependent on `frequencies.json` since https://github.com/Ousret/charset_normalizer/releases/tag/2.0.1 https://github.com/Ousret/charset_normalizer/pull/55
Yet you mention v2.0.4, 

Either something is wrong with the `Conda package` and I am not the package maintainer at Conda, or you have two versions installed/conflict. Make sure that you have only the latest installed.

**Comment by hjs-develop** [comment]
Thank you for your swift rely.

I solved it to us in the conda environment pip to install von PyPi and not Anaconda repro. So it is definitly a bug of the package charset-normalizer==2.0.4 used as Conda package.

Thanks again!
HJ.
